### ISSUE TITLE
Excuse me

### ISSUE THREAD

**Issue by MyTuring** [Kojey/MSc-whistler-waves-detector#1]
Excuse me，I want to ask how to generate train_test.pickle.And i couldn't find the data......

**Comment by MyTuring** [comment]
And no h5 files,no sample_detector.py

**Comment by MyTuring** [comment]
> Excuse me，I want to ask how to generate train_test.pickle.And i couldn't find the data......

**Comment by Kojey** [comment]
Hi 
Sorry for the delay, I haven't been active on this account.

Here is a link to the data: [whistler data](https://drive.google.com/drive/folders/17gXDfkuVt8HJ1tu5o-keknaBjzCI1G-9)
I'll advise that you follow the chapter in the dissertation and use the corresponding code under `ipy/report` to generate any figures shown in the report.
[MSc_Thesis.pdf](https://github.com/Kojey/MSc-whistler-waves-detector/files/5557868/MSc_Thesis.pdf)

**Comment by MyTuring** [comment]
I am very happy to receive your reply. I have done something according to the code you provided. At last, I really appreciate your reply.




回复
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kojey/MSc-whistler-waves-detector"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月18日(星期三) 中午1:06
收件人:&nbsp;"Kojey/MSc-whistler-waves-detector"<MSc-whistler-waves-detector@noreply.github.com&gt;;
抄送:&nbsp;"思无邪"<1399277796@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Kojey/MSc-whistler-waves-detector] Excuse me (#1)





 
Hi
 Sorry for the delay, I haven't been active on this account.
 
Here is a link to the data: whistler data
 I'll advise that you follow the chapter in the dissertation and use the corresponding code under ipy/report to generate any figures shown in the report.
 MSc_Thesis.pdf
